networks:
  my_local_net:
    name: my_local_net
    driver: bridge

services:
  gui:
    build: ./gui
    restart: always
    ports:
      - "5000:5000"
    networks:
      - my_local_net

  authentication-db:
    image: docker.io/postgres:latest
    restart: always
    environment:
      POSTGRES_DB: authentication-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - authentication_db_data:/var/lib/postgresql/data
    networks:
      - my_local_net

  authentication:
    build: ./authentication
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - authentication-db
    networks:
      - my_local_net

  event-management-db:
    image: docker.io/postgres:latest
    restart: always
    environment:
      POSTGRES_DB: event-management-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - event_management_db_data:/var/lib/postgresql/data
    networks:
      - my_local_net

  event-management:
    build: ./event-management
    restart: always
    ports:
      - "5002:5002"
    depends_on:
      - event-management-db
    networks:
      - my_local_net

  calendar-db:
    image: docker.io/postgres:latest
    restart: always
    environment:
      POSTGRES_DB: calendar-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - calendar_db_data:/var/lib/postgresql/data
    networks:
      - my_local_net

  calendar:
    build: ./calendar
    restart: always
    ports:
      - "5003:5003"
    depends_on:
      - calendar-db
    networks:
      - my_local_net

volumes:
  authentication_db_data:
  event_management_db_data:
  calendar_db_data:
